name: Build with Nuitka

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install nuitka
        pip install -r requirements.txt

    - name: Build
      run: |
        python -m nuitka `
          --standalone `
          --windows-console-mode=disable `
          --windows-icon-from-ico=logo.ico `
          --output-dir=build_output `
          --output-filename=百度翻译.exe `
          --enable-plugin=pyqt6 `
          --jobs=2 `
          --assume-yes-for-downloads `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: EmployeeLauncher
        path: build_output/
